apiVersion: v1
kind: ReplicationController
metadata:
  name: kitten
spec:
  selector:
    name: update-demo
    version: kitten-v1
  template:
    metadata:
      labels:
        name: update-demo
        version: kitten-v1
    spec:
      containers:
      - image: gcr.io/google_containers/update-demo:kitten
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
