apiVersion: v1
kind: ReplicationController
# metadata contains: name, labels, annotations.
# name is the resource id
metadata:
  name: snail
# spec: previously named desiredState
# status: previously named currentState
spec:
  replicas: 2
  selector:
    name: update-demo
    version: snail-v1
  template:
    metadata:
      labels:
        name: update-demo
        version: snail-v1
    spec:
      containers:
      - image: gcr.io/google_containers/update-demo:nautilus
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP

